-- MySQL Script generated by MySQL Workbench
-- lun 30 mar 2020 10:13:57 -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema builder
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `priv_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `priv_role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` CHAR(100) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `priv_capability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `priv_capability` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` CHAR(250) NOT NULL,
  `description` TEXT NULL,
  `category_id` BIGINT NOT NULL DEFAULT 1 COMMENT 'ref to closure_caterory.id',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC),
  INDEX `category_id` (`category_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `priv_role_has_capability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `priv_role_has_capability` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `role_id` BIGINT NOT NULL,
  `capability_id` BIGINT NOT NULL,
  INDEX `cap_id` (`capability_id` ASC),
  INDEX `role_id` (`role_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique` (`role_id` ASC, `capability_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `priv_user_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `priv_user_has_role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `role_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `role_id` (`role_id` ASC),
  UNIQUE INDEX `unique` (`user_id` ASC, `role_id` ASC),
  INDEX `user_id` (`user_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `type` CHAR(50) NOT NULL,
  `created_on` DATETIME NOT NULL,
  `timezone` VARCHAR(50) NOT NULL,
  `method` VARCHAR(150) NULL,
  `ref` CHAR(250) NULL,
  `message` CHAR(250) NULL,
  `extra` LONGTEXT NULL,
  `get` TEXT NULL,
  `post` TEXT NULL,
  `headers` TEXT NULL,
  `body` LONGTEXT NULL,
  `url` TEXT NULL,
  `file` LONGTEXT NULL,
  `cookies` TEXT NULL,
  `session` TEXT NULL,
  `agent` TEXT NULL,
  `ip_address` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `type` (`type` ASC),
  INDEX `created_on` (`created_on` ASC),
  INDEX `ref` (`ref` ASC),
  INDEX `message` (`message` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `session` (
  `id` CHAR(32) NOT NULL,
  `name` CHAR(32) NOT NULL,
  `modified` INT NULL,
  `lifetime` INT NULL,
  `data` TEXT NULL,
  `user_id` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `closure_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `closure_group` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` CHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `closure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `closure` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `parent_id` BIGINT NOT NULL,
  `child_id` BIGINT NOT NULL,
  `depth` BIGINT NOT NULL DEFAULT 0,
  `group_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `parent_id` (`parent_id` ASC),
  INDEX `child_id` (`child_id` ASC),
  INDEX `group_id` (`group_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `closure_node`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `closure_node` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` CHAR(150) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `audit_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audit_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_on` DATETIME NOT NULL,
  `title` CHAR(100) NOT NULL,
  `url` TEXT NOT NULL,
  `ip_address` CHAR(45) NOT NULL,
  `user_id` CHAR(50) NULL,
  `detail` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `title` (`title` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `closure_sort`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `closure_sort` (
  `group_id` BIGINT NOT NULL,
  `node_id` BIGINT NOT NULL,
  `sort` BIGINT NOT NULL,
  UNIQUE INDEX `unique` (`group_id` ASC, `node_id` ASC),
  INDEX `sort` (`sort` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `parallel_instance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parallel_instance` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `number` BIGINT NOT NULL,
  `script` CHAR(250) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `u` (`number` ASC, `script` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parallel_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parallel_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `item_id` CHAR(250) NULL,
  `started_on` DATETIME NULL,
  `finished_on` DATETIME NULL,
  `error` LONGTEXT NULL,
  `data` VARCHAR(250) NULL,
  `instance_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_parallel_item_parallel_instance1_idx` (`instance_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `priv_role`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `priv_role` (`id`, `name`, `description`) VALUES (1, 'super admin', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `priv_user_has_role`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `priv_user_has_role` (`id`, `user_id`, `role_id`) VALUES (1, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `closure_group`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `closure_group` (`id`, `name`) VALUES (1, 'priv');

COMMIT;


-- -----------------------------------------------------
-- Data for table `closure`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `closure` (`id`, `parent_id`, `child_id`, `depth`, `group_id`) VALUES (1, 1, 1, 0, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `closure_node`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `closure_node` (`id`, `name`, `description`) VALUES (1, 'def', NULL);
INSERT INTO `closure_node` (`id`, `name`, `description`) VALUES (2, 'Global permissions', NULL);

COMMIT;

